# Generated by Django 4.1.7 on 2023-05-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='slogon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
