# Generated by Django 4.2.1 on 2023-05-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsactivation',
            name='email',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
